### ISSUE TITLE
`instagram` command doesn't work

### ISSUE THREAD

**Issue by eitozx** [NixonXC/Venox#3]
I don't know if you're aware of this.. but to use
`https://www.instagram.com/{user}/channel/?__a=1`
or `https://www.instagram.com/{user}/?__a=1`

you need to have your account logged in already.
Try to open these links in incognito mode where you haven't logged in & you'll see.
Hence: Command doesn't work.

but there is an alternative to this.. u can use: [Instagram API](https://developers.facebook.com/docs/instagram-api/ ) for this if you want.

**Comment by NixonXC** [comment]
Thanks for the suggestion, I'm still trying to find a good package for instagram so yeah it will take some time.

**Comment by eitozx** [comment]
I'm not sure if there's any package made for instagram yet.. and [Instagram API](https://developers.facebook.com/docs/instagram-api/) is the official one. Anyways, feel free to ping if you need help anywhere.

**Comment by NixonXC** [comment]
Np, thanks for the help, I came around a few packages they were not working anymore tho (instagramy)
